import type {
  BenchmarkCondition,
  InjectionMode,
  InjectPdfInput,
  PrivateManifest,
} from "@pdf-injection/contracts";
import { injectPdf } from "@pdf-injection/pdf-engine";
import { sha256Hex } from "@pdf-injection/validation";
import type { AppConfig } from "../config";
import { jobArtifactExists, readJobArtifactBytes, writeJobArtifact } from "../lib/job-artifacts";
import { readJobFileBytes, readJobFileText } from "../storage";

export interface ConditionPdf {
  condition: BenchmarkCondition;
  bytes: Uint8Array;
  sha256: string;
}

const INJECTABLE_CONDITIONS: InjectionMode[] = [
  "white_text",
  "render_mode_3",
  "visible_positive_control",
  "xmp_only",
];

function isInjectionMode(condition: BenchmarkCondition): condition is InjectionMode {
  return (INJECTABLE_CONDITIONS as string[]).includes(condition);
}

/**
 * Returns the PDF bytes for a `BenchmarkCondition`/`PdfTransform` source of a
 * completed job, generating + caching on first use. `"original"` is always
 * the job's `source.pdf`, verbatim (no cache needed). Every injected
 * condition is generated by re-running `injectPdf()` with the job's own
 * stored instruction/settings (read from `manifest.json` — never logged) for
 * that specific mode, cached at `<jobDir>/conditions/<mode>.pdf` so repeated
 * model-test / robustness runs against the same job reuse it instead of
 * re-running pdf-lib injection every time (contract §2: "Condition PDFs
 * generated from the job's stored source + the job's instruction/settings
 * for every listed mode (cached at `<jobDir>/conditions/<mode>.pdf`)").
 */
export async function getConditionPdf(
  config: AppConfig,
  jobId: string,
  condition: BenchmarkCondition,
): Promise<ConditionPdf> {
  if (condition === "original") {
    const bytes = await readJobFileBytes(config, jobId, "source.pdf");
    return { condition, bytes, sha256: sha256Hex(bytes) };
  }

  if (!isInjectionMode(condition)) {
    throw new Error(`Unknown benchmark condition: ${condition}`);
  }

  const cacheSegments = ["conditions", `${condition}.pdf`];
  if (await jobArtifactExists(config, jobId, cacheSegments)) {
    const bytes = await readJobArtifactBytes(config, jobId, cacheSegments);
    return { condition, bytes, sha256: sha256Hex(bytes) };
  }

  const manifestText = await readJobFileText(config, jobId, "manifest.json");
  const manifest = JSON.parse(manifestText) as PrivateManifest;
  const sourceBytes = await readJobFileBytes(config, jobId, "source.pdf");

  const injectionInput: InjectPdfInput = {
    source: sourceBytes,
    instruction: manifest.prompt.instruction,
    mode: condition,
    // manifest.injection.pageIndex is the already-resolved 0-based index;
    // +1 converts it back to the 1-based TargetPage injectPdf's own
    // resolveTargetPage() expects.
    targetPage: manifest.injection.pageIndex + 1,
    position: manifest.injection.position,
    fontSize: manifest.injection.fontSize,
    payloadLanguage: manifest.prompt.language,
  };

  if (manifest.injection.position === "custom") {
    // manifest.injection only stores the *resulting* boundingBox
    // ([minX, minY, maxX, maxY]), not the original x/y anchor that was
    // passed in. [minX, minY] closely approximates the original anchor —
    // sufficient here since this regenerated PDF feeds provider
    // benchmarking / robustness transforms, not an exact pixel-identical
    // reproduction of the job's own output.pdf.
    injectionInput.x = manifest.injection.boundingBox[0];
    injectionInput.y = manifest.injection.boundingBox[1];
  }

  const result = await injectPdf(injectionInput);
  await writeJobArtifact(config, jobId, cacheSegments, result.bytes);
  return { condition, bytes: result.bytes, sha256: sha256Hex(result.bytes) };
}
